/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project2;

import java.util.Scanner;

/**
 *
 * @author rbhal
 */
public class PlayerGUI extends javax.swing.JFrame{

    /**
     * Creates new form PlayerGUI
     */
    public PlayerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        And = new javax.swing.JLabel();
        Fungeons = new javax.swing.JLabel();
        Dragons = new javax.swing.JLabel();
        CharacterCreation = new javax.swing.JLabel();
        enterCharFName = new javax.swing.JLabel();
        CharLName = new javax.swing.JTextField();
        LastName2 = new javax.swing.JLabel();
        baseStatsTitle = new javax.swing.JLabel();
        tieflingInt = new javax.swing.JLabel();
        dragonBornStr = new javax.swing.JLabel();
        dragonBornChar = new javax.swing.JLabel();
        dwarfConst = new javax.swing.JLabel();
        elfDex = new javax.swing.JLabel();
        elfWis = new javax.swing.JLabel();
        gnomeInt = new javax.swing.JLabel();
        halfElfChar = new javax.swing.JLabel();
        bardSaves = new javax.swing.JLabel();
        halfOrcConst = new javax.swing.JLabel();
        halfOrdConst = new javax.swing.JLabel();
        humanAllAttr = new javax.swing.JLabel();
        tieflingChar = new javax.swing.JLabel();
        CharFName = new javax.swing.JTextField();
        wizardButton = new javax.swing.JButton();
        dragonBornButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        dwarfButton = new javax.swing.JButton();
        elfButton = new javax.swing.JButton();
        gnomeButton = new javax.swing.JButton();
        halfElfButton = new javax.swing.JButton();
        halfingButton = new javax.swing.JButton();
        halfOrcButton = new javax.swing.JButton();
        humanButton = new javax.swing.JButton();
        enterCharLName = new javax.swing.JLabel();
        raceTitle = new javax.swing.JLabel();
        tieflingButton = new javax.swing.JButton();
        barbarianButton = new javax.swing.JButton();
        bardButton = new javax.swing.JButton();
        clericButton = new javax.swing.JButton();
        druidButton = new javax.swing.JButton();
        fighterButton = new javax.swing.JButton();
        monkButton = new javax.swing.JButton();
        paladinButton = new javax.swing.JButton();
        rangerButton = new javax.swing.JButton();
        rogueButton = new javax.swing.JButton();
        sorcerorButton = new javax.swing.JButton();
        warlockButton = new javax.swing.JButton();
        halfingDex = new javax.swing.JLabel();
        bardHitDie = new javax.swing.JLabel();
        bardPrimAbility = new javax.swing.JLabel();
        barbHitDie = new javax.swing.JLabel();
        barbPrimAbility = new javax.swing.JLabel();
        barbSaves = new javax.swing.JLabel();
        clericSaves = new javax.swing.JLabel();
        clericHitDie = new javax.swing.JLabel();
        clericPrimAbility = new javax.swing.JLabel();
        druidSaves = new javax.swing.JLabel();
        druidHitDie = new javax.swing.JLabel();
        druidPrimAbility = new javax.swing.JLabel();
        fighterSaves = new javax.swing.JLabel();
        fighterHitDie = new javax.swing.JLabel();
        fighterPrimAbility = new javax.swing.JLabel();
        monkSaves = new javax.swing.JLabel();
        monkHitDie = new javax.swing.JLabel();
        monkPrimAbility = new javax.swing.JLabel();
        paladinSaves = new javax.swing.JLabel();
        paladinPrimAbility = new javax.swing.JLabel();
        rangerSaves = new javax.swing.JLabel();
        rangerHitDie = new javax.swing.JLabel();
        rangerPrimAbility = new javax.swing.JLabel();
        rogueSaves = new javax.swing.JLabel();
        rogueHitDie = new javax.swing.JLabel();
        roguePrimAbility = new javax.swing.JLabel();
        sorcerorSaves = new javax.swing.JLabel();
        sorcerorHitDie = new javax.swing.JLabel();
        sorcerorPrimAbility = new javax.swing.JLabel();
        warlockSaves = new javax.swing.JLabel();
        warlockHitDie = new javax.swing.JLabel();
        warlockPrimAbility = new javax.swing.JLabel();
        wizardSaves = new javax.swing.JLabel();
        wizardHitDie = new javax.swing.JLabel();
        wizardPrimAbility = new javax.swing.JLabel();
        classTitle = new javax.swing.JLabel();
        paladinHitDie = new javax.swing.JLabel();
        strength = new javax.swing.JLabel();
        dexterity = new javax.swing.JLabel();
        constitution = new javax.swing.JLabel();
        intelligence = new javax.swing.JLabel();
        wisdom = new javax.swing.JLabel();
        charisma = new javax.swing.JLabel();
        charismaStat = new javax.swing.JTextField();
        strengthStat = new javax.swing.JTextField();
        DexterityStat = new javax.swing.JTextField();
        constitutionStat = new javax.swing.JTextField();
        intelligenceStat = new javax.swing.JTextField();
        wisdomStat = new javax.swing.JTextField();
        lessChar = new javax.swing.JButton();
        moreStr = new javax.swing.JButton();
        moreDex = new javax.swing.JButton();
        moreConst = new javax.swing.JButton();
        moreInt = new javax.swing.JButton();
        moreWis = new javax.swing.JButton();
        moreChar = new javax.swing.JButton();
        lessStr = new javax.swing.JButton();
        lessDex = new javax.swing.JButton();
        lessConst = new javax.swing.JButton();
        lessInt = new javax.swing.JButton();
        lessWis = new javax.swing.JButton();
        LastName7 = new javax.swing.JLabel();
        LastName8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(54, 6, 43));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        And.setFont(new java.awt.Font("Old English Text MT", 2, 70)); // NOI18N
        And.setForeground(new java.awt.Color(255, 255, 255));
        And.setText("&");
        And.setToolTipText("");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, And, org.jdesktop.beansbinding.ObjectProperty.create(), And, org.jdesktop.beansbinding.BeanProperty.create("labelFor"));
        bindingGroup.addBinding(binding);

        jPanel1.add(And, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 60, 60));

        Fungeons.setFont(new java.awt.Font("Old English Text MT", 1, 48)); // NOI18N
        Fungeons.setForeground(new java.awt.Color(255, 255, 255));
        Fungeons.setText("Fungeons");
        Fungeons.setToolTipText("");
        jPanel1.add(Fungeons, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 260, 60));

        Dragons.setFont(new java.awt.Font("Old English Text MT", 1, 48)); // NOI18N
        Dragons.setForeground(new java.awt.Color(255, 255, 255));
        Dragons.setText("Dragons");
        Dragons.setToolTipText("");
        jPanel1.add(Dragons, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 260, 60));

        CharacterCreation.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        CharacterCreation.setForeground(new java.awt.Color(255, 255, 255));
        CharacterCreation.setText("Character Creation");
        CharacterCreation.setToolTipText("");
        jPanel1.add(CharacterCreation, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 200, 30));

        enterCharFName.setFont(new java.awt.Font("Old English Text MT", 1, 18)); // NOI18N
        enterCharFName.setForeground(new java.awt.Color(255, 255, 255));
        enterCharFName.setText("Enter Character's First name:");
        enterCharFName.setToolTipText("");
        jPanel1.add(enterCharFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 280, 20));

        CharLName.setFont(new java.awt.Font("Old English Text MT", 0, 12)); // NOI18N
        CharLName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CharLNameActionPerformed(evt);
            }
        });
        jPanel1.add(CharLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 120, 20));

        LastName2.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName2.setForeground(new java.awt.Color(255, 255, 255));
        LastName2.setText("Choose base Stats:");
        LastName2.setToolTipText("");
        jPanel1.add(LastName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 270, 230, 30));

        baseStatsTitle.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        baseStatsTitle.setForeground(new java.awt.Color(255, 255, 255));
        baseStatsTitle.setText("Base Stats");
        baseStatsTitle.setToolTipText("");
        jPanel1.add(baseStatsTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 220, 120, 30));

        tieflingInt.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        tieflingInt.setForeground(new java.awt.Color(255, 255, 255));
        tieflingInt.setText("+1 Intelligence");
        tieflingInt.setToolTipText("");
        jPanel1.add(tieflingInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 590, 100, 30));

        dragonBornStr.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        dragonBornStr.setForeground(new java.awt.Color(255, 255, 255));
        dragonBornStr.setText("+2 Strength");
        dragonBornStr.setToolTipText("");
        jPanel1.add(dragonBornStr, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 80, 30));

        dragonBornChar.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        dragonBornChar.setForeground(new java.awt.Color(255, 255, 255));
        dragonBornChar.setText("+1 Charisma");
        dragonBornChar.setToolTipText("");
        jPanel1.add(dragonBornChar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 90, 30));

        dwarfConst.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        dwarfConst.setForeground(new java.awt.Color(255, 255, 255));
        dwarfConst.setText("+2 Constitution");
        dwarfConst.setToolTipText("");
        jPanel1.add(dwarfConst, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 100, 30));

        elfDex.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        elfDex.setForeground(new java.awt.Color(255, 255, 255));
        elfDex.setText("+2 Dexterity");
        elfDex.setToolTipText("");
        jPanel1.add(elfDex, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 100, 30));

        elfWis.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        elfWis.setForeground(new java.awt.Color(255, 255, 255));
        elfWis.setText("+1 Wisdom");
        elfWis.setToolTipText("");
        jPanel1.add(elfWis, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 100, 30));

        gnomeInt.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        gnomeInt.setForeground(new java.awt.Color(255, 255, 255));
        gnomeInt.setText("+2 Intelligence");
        gnomeInt.setToolTipText("");
        jPanel1.add(gnomeInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 100, 30));

        halfElfChar.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        halfElfChar.setForeground(new java.awt.Color(255, 255, 255));
        halfElfChar.setText("+2 Charisma");
        halfElfChar.setToolTipText("");
        jPanel1.add(halfElfChar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 100, 30));

        bardSaves.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        bardSaves.setForeground(new java.awt.Color(255, 255, 255));
        bardSaves.setText("Saves: Dexterity & Charisma");
        bardSaves.setToolTipText("");
        jPanel1.add(bardSaves, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 200, 30));

        halfOrcConst.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        halfOrcConst.setForeground(new java.awt.Color(255, 255, 255));
        halfOrcConst.setText("+2 Strength");
        halfOrcConst.setToolTipText("");
        jPanel1.add(halfOrcConst, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 100, 30));

        halfOrdConst.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        halfOrdConst.setForeground(new java.awt.Color(255, 255, 255));
        halfOrdConst.setText("+1 Constitution");
        halfOrdConst.setToolTipText("");
        jPanel1.add(halfOrdConst, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 100, 30));

        humanAllAttr.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        humanAllAttr.setForeground(new java.awt.Color(255, 255, 255));
        humanAllAttr.setText("+1 to All Attributes");
        humanAllAttr.setToolTipText("");
        jPanel1.add(humanAllAttr, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 130, 30));

        tieflingChar.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        tieflingChar.setForeground(new java.awt.Color(255, 255, 255));
        tieflingChar.setText("+2 Charisma");
        tieflingChar.setToolTipText("");
        jPanel1.add(tieflingChar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 570, 90, 30));

        CharFName.setFont(new java.awt.Font("Old English Text MT", 0, 12)); // NOI18N
        CharFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CharFNameActionPerformed(evt);
            }
        });
        jPanel1.add(CharFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 120, 20));

        wizardButton.setBackground(new java.awt.Color(204, 204, 204));
        wizardButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        wizardButton.setText("Wizard");
        wizardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wizardButtonActionPerformed(evt);
            }
        });
        jPanel1.add(wizardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 800, 120, 30));

        dragonBornButton.setBackground(new java.awt.Color(204, 204, 204));
        dragonBornButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        dragonBornButton.setText("Dragonborn");
        dragonBornButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dragonBornButtonActionPerformed(evt);
            }
        });
        jPanel1.add(dragonBornButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 120, 30));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        jButton3.setText("Dragonborn");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 120, 30));

        dwarfButton.setBackground(new java.awt.Color(204, 204, 204));
        dwarfButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        dwarfButton.setText("Dwarf");
        dwarfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dwarfButtonActionPerformed(evt);
            }
        });
        jPanel1.add(dwarfButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 120, 30));

        elfButton.setBackground(new java.awt.Color(204, 204, 204));
        elfButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        elfButton.setText("Elf");
        elfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elfButtonActionPerformed(evt);
            }
        });
        jPanel1.add(elfButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 120, 30));

        gnomeButton.setBackground(new java.awt.Color(204, 204, 204));
        gnomeButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        gnomeButton.setText("Gnome");
        gnomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gnomeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(gnomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 120, 30));

        halfElfButton.setBackground(new java.awt.Color(204, 204, 204));
        halfElfButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        halfElfButton.setText("Half-Elf");
        halfElfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                halfElfButtonActionPerformed(evt);
            }
        });
        jPanel1.add(halfElfButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 120, 30));

        halfingButton.setBackground(new java.awt.Color(204, 204, 204));
        halfingButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        halfingButton.setText("Halfing");
        halfingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                halfingButtonActionPerformed(evt);
            }
        });
        jPanel1.add(halfingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 120, 30));

        halfOrcButton.setBackground(new java.awt.Color(204, 204, 204));
        halfOrcButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        halfOrcButton.setText("Half-Orc");
        halfOrcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                halfOrcButtonActionPerformed(evt);
            }
        });
        jPanel1.add(halfOrcButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 120, 30));

        humanButton.setBackground(new java.awt.Color(204, 204, 204));
        humanButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        humanButton.setText("Human");
        humanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                humanButtonActionPerformed(evt);
            }
        });
        jPanel1.add(humanButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 120, 30));

        enterCharLName.setFont(new java.awt.Font("Old English Text MT", 1, 18)); // NOI18N
        enterCharLName.setForeground(new java.awt.Color(255, 255, 255));
        enterCharLName.setText("Enter Character's last name:");
        enterCharLName.setToolTipText("");
        jPanel1.add(enterCharLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 270, 30));

        raceTitle.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        raceTitle.setForeground(new java.awt.Color(255, 255, 255));
        raceTitle.setText("Race");
        raceTitle.setToolTipText("");
        jPanel1.add(raceTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 60, 30));

        tieflingButton.setBackground(new java.awt.Color(204, 204, 204));
        tieflingButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        tieflingButton.setText("Tiefling");
        tieflingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tieflingButtonActionPerformed(evt);
            }
        });
        jPanel1.add(tieflingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 540, 120, 30));

        barbarianButton.setBackground(new java.awt.Color(204, 204, 204));
        barbarianButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        barbarianButton.setText("Bardarian");
        barbarianButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barbarianButtonActionPerformed(evt);
            }
        });
        jPanel1.add(barbarianButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 120, 30));

        bardButton.setBackground(new java.awt.Color(204, 204, 204));
        bardButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        bardButton.setText("Bard");
        bardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bardButtonActionPerformed(evt);
            }
        });
        jPanel1.add(bardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 120, 30));

        clericButton.setBackground(new java.awt.Color(204, 204, 204));
        clericButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        clericButton.setText("Cleric");
        clericButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clericButtonActionPerformed(evt);
            }
        });
        jPanel1.add(clericButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, 120, 30));

        druidButton.setBackground(new java.awt.Color(204, 204, 204));
        druidButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        druidButton.setText("Druid");
        druidButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                druidButtonActionPerformed(evt);
            }
        });
        jPanel1.add(druidButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 600, 120, 30));

        fighterButton.setBackground(new java.awt.Color(204, 204, 204));
        fighterButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        fighterButton.setText("Fighter");
        fighterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fighterButtonActionPerformed(evt);
            }
        });
        jPanel1.add(fighterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 700, 120, 30));

        monkButton.setBackground(new java.awt.Color(204, 204, 204));
        monkButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        monkButton.setText("Monk");
        monkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monkButtonActionPerformed(evt);
            }
        });
        jPanel1.add(monkButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 800, 120, 30));

        paladinButton.setBackground(new java.awt.Color(204, 204, 204));
        paladinButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        paladinButton.setText("Paladin");
        paladinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paladinButtonActionPerformed(evt);
            }
        });
        jPanel1.add(paladinButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 120, 30));

        rangerButton.setBackground(new java.awt.Color(204, 204, 204));
        rangerButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        rangerButton.setText("Ranger");
        rangerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rangerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(rangerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 120, 30));

        rogueButton.setBackground(new java.awt.Color(204, 204, 204));
        rogueButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        rogueButton.setText("Rogue");
        rogueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rogueButtonActionPerformed(evt);
            }
        });
        jPanel1.add(rogueButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 500, 120, 30));

        sorcerorButton.setBackground(new java.awt.Color(204, 204, 204));
        sorcerorButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        sorcerorButton.setText("Sorceror");
        sorcerorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sorcerorButtonActionPerformed(evt);
            }
        });
        jPanel1.add(sorcerorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 600, 120, 30));

        warlockButton.setBackground(new java.awt.Color(204, 204, 204));
        warlockButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        warlockButton.setText("Warlock");
        warlockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warlockButtonActionPerformed(evt);
            }
        });
        jPanel1.add(warlockButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 700, 120, 30));

        halfingDex.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        halfingDex.setForeground(new java.awt.Color(255, 255, 255));
        halfingDex.setText("+2 Dexterity");
        halfingDex.setToolTipText("");
        jPanel1.add(halfingDex, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 100, 30));

        bardHitDie.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        bardHitDie.setForeground(new java.awt.Color(255, 255, 255));
        bardHitDie.setText("Hit Die: d8");
        bardHitDie.setToolTipText("");
        jPanel1.add(bardHitDie, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 80, 30));

        bardPrimAbility.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        bardPrimAbility.setForeground(new java.awt.Color(255, 255, 255));
        bardPrimAbility.setText("Primary Abilility: Charisma");
        bardPrimAbility.setToolTipText("");
        jPanel1.add(bardPrimAbility, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 180, 30));

        barbHitDie.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        barbHitDie.setForeground(new java.awt.Color(255, 255, 255));
        barbHitDie.setText("Hit Die: d12");
        barbHitDie.setToolTipText("");
        jPanel1.add(barbHitDie, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 90, 30));

        barbPrimAbility.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        barbPrimAbility.setForeground(new java.awt.Color(255, 255, 255));
        barbPrimAbility.setText("Primary Abilility: Strength");
        barbPrimAbility.setToolTipText("");
        jPanel1.add(barbPrimAbility, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 180, 30));

        barbSaves.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        barbSaves.setForeground(new java.awt.Color(255, 255, 255));
        barbSaves.setText("Saves: Strength & Constitution");
        barbSaves.setToolTipText("");
        jPanel1.add(barbSaves, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 210, 30));

        clericSaves.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        clericSaves.setForeground(new java.awt.Color(255, 255, 255));
        clericSaves.setText("Saves: Wisdom & Charisma");
        clericSaves.setToolTipText("");
        jPanel1.add(clericSaves, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 570, 190, 30));

        clericHitDie.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        clericHitDie.setForeground(new java.awt.Color(255, 255, 255));
        clericHitDie.setText("Hit Die: d8");
        clericHitDie.setToolTipText("");
        jPanel1.add(clericHitDie, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, 80, 30));

        clericPrimAbility.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        clericPrimAbility.setForeground(new java.awt.Color(255, 255, 255));
        clericPrimAbility.setText("Primary Abilility: Wisdom");
        clericPrimAbility.setToolTipText("");
        jPanel1.add(clericPrimAbility, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 550, 170, 30));

        druidSaves.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        druidSaves.setForeground(new java.awt.Color(255, 255, 255));
        druidSaves.setText("Saves: Intelligence & Wisdom");
        druidSaves.setToolTipText("");
        jPanel1.add(druidSaves, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 670, 200, 30));

        druidHitDie.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        druidHitDie.setForeground(new java.awt.Color(255, 255, 255));
        druidHitDie.setText("Hit Die: d8");
        druidHitDie.setToolTipText("");
        jPanel1.add(druidHitDie, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 630, 100, 30));

        druidPrimAbility.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        druidPrimAbility.setForeground(new java.awt.Color(255, 255, 255));
        druidPrimAbility.setText("Primary Abilility: Wisdom");
        druidPrimAbility.setToolTipText("");
        jPanel1.add(druidPrimAbility, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 650, 170, 30));

        fighterSaves.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        fighterSaves.setForeground(new java.awt.Color(255, 255, 255));
        fighterSaves.setText("Saves: Strength & Constitution");
        fighterSaves.setToolTipText("");
        jPanel1.add(fighterSaves, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 770, 210, 30));

        fighterHitDie.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        fighterHitDie.setForeground(new java.awt.Color(255, 255, 255));
        fighterHitDie.setText("Hit Die: d10");
        fighterHitDie.setToolTipText("");
        jPanel1.add(fighterHitDie, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 730, 100, 30));

        fighterPrimAbility.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        fighterPrimAbility.setForeground(new java.awt.Color(255, 255, 255));
        fighterPrimAbility.setText("Primary Abilility: Strength or Dexterity");
        fighterPrimAbility.setToolTipText("");
        jPanel1.add(fighterPrimAbility, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 750, 250, 30));

        monkSaves.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        monkSaves.setForeground(new java.awt.Color(255, 255, 255));
        monkSaves.setText("Saves: Strength & Dexterity");
        monkSaves.setToolTipText("");
        jPanel1.add(monkSaves, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 870, 190, 30));

        monkHitDie.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        monkHitDie.setForeground(new java.awt.Color(255, 255, 255));
        monkHitDie.setText("Hit Die: d8");
        monkHitDie.setToolTipText("");
        jPanel1.add(monkHitDie, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 830, 100, 30));

        monkPrimAbility.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        monkPrimAbility.setForeground(new java.awt.Color(255, 255, 255));
        monkPrimAbility.setText("Primary Abilility: Dexterity & Wisdom");
        monkPrimAbility.setToolTipText("");
        jPanel1.add(monkPrimAbility, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 850, 250, 30));

        paladinSaves.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        paladinSaves.setForeground(new java.awt.Color(255, 255, 255));
        paladinSaves.setText("Saves: Wisdom & Charisma");
        paladinSaves.setToolTipText("");
        jPanel1.add(paladinSaves, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 190, 30));

        paladinPrimAbility.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        paladinPrimAbility.setForeground(new java.awt.Color(255, 255, 255));
        paladinPrimAbility.setText("Primary Abilility: Strength & Charisma");
        paladinPrimAbility.setToolTipText("");
        jPanel1.add(paladinPrimAbility, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, 250, 30));

        rangerSaves.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        rangerSaves.setForeground(new java.awt.Color(255, 255, 255));
        rangerSaves.setText("Saves: Strength & Dexterity");
        rangerSaves.setToolTipText("");
        jPanel1.add(rangerSaves, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 470, 190, 30));

        rangerHitDie.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        rangerHitDie.setForeground(new java.awt.Color(255, 255, 255));
        rangerHitDie.setText("Hit Die: d10");
        rangerHitDie.setToolTipText("");
        jPanel1.add(rangerHitDie, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, 90, 30));

        rangerPrimAbility.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        rangerPrimAbility.setForeground(new java.awt.Color(255, 255, 255));
        rangerPrimAbility.setText("Primary Abilility: Dexterity & Wisdom");
        rangerPrimAbility.setToolTipText("");
        jPanel1.add(rangerPrimAbility, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, 250, 30));

        rogueSaves.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        rogueSaves.setForeground(new java.awt.Color(255, 255, 255));
        rogueSaves.setText("Saves: Dexterity & Intelligence");
        rogueSaves.setToolTipText("");
        jPanel1.add(rogueSaves, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 570, 210, 30));

        rogueHitDie.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        rogueHitDie.setForeground(new java.awt.Color(255, 255, 255));
        rogueHitDie.setText("Hit Die: d8");
        rogueHitDie.setToolTipText("");
        jPanel1.add(rogueHitDie, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 530, 80, 30));

        roguePrimAbility.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        roguePrimAbility.setForeground(new java.awt.Color(255, 255, 255));
        roguePrimAbility.setText("Primary Abilility: Dexterity ");
        roguePrimAbility.setToolTipText("");
        jPanel1.add(roguePrimAbility, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 550, 180, 30));

        sorcerorSaves.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        sorcerorSaves.setForeground(new java.awt.Color(255, 255, 255));
        sorcerorSaves.setText("Saves: Constitution & Charisma");
        sorcerorSaves.setToolTipText("");
        jPanel1.add(sorcerorSaves, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 670, 210, 30));

        sorcerorHitDie.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        sorcerorHitDie.setForeground(new java.awt.Color(255, 255, 255));
        sorcerorHitDie.setText("Hit Die: d6");
        sorcerorHitDie.setToolTipText("");
        jPanel1.add(sorcerorHitDie, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 630, 80, 30));

        sorcerorPrimAbility.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        sorcerorPrimAbility.setForeground(new java.awt.Color(255, 255, 255));
        sorcerorPrimAbility.setText("Primary Abilility: Charisma");
        sorcerorPrimAbility.setToolTipText("");
        jPanel1.add(sorcerorPrimAbility, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 650, 180, 30));

        warlockSaves.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        warlockSaves.setForeground(new java.awt.Color(255, 255, 255));
        warlockSaves.setText("Saves: Wisdom & Charisma");
        warlockSaves.setToolTipText("");
        jPanel1.add(warlockSaves, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 770, 190, 30));

        warlockHitDie.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        warlockHitDie.setForeground(new java.awt.Color(255, 255, 255));
        warlockHitDie.setText("Hit Die: d8");
        warlockHitDie.setToolTipText("");
        jPanel1.add(warlockHitDie, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 730, 80, 30));

        warlockPrimAbility.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        warlockPrimAbility.setForeground(new java.awt.Color(255, 255, 255));
        warlockPrimAbility.setText("Primary Abilility: Charisma");
        warlockPrimAbility.setToolTipText("");
        jPanel1.add(warlockPrimAbility, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 750, 180, 30));

        wizardSaves.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        wizardSaves.setForeground(new java.awt.Color(255, 255, 255));
        wizardSaves.setText("Saves: Intelligence & Wisdom");
        wizardSaves.setToolTipText("");
        jPanel1.add(wizardSaves, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 870, 200, 30));

        wizardHitDie.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        wizardHitDie.setForeground(new java.awt.Color(255, 255, 255));
        wizardHitDie.setText("Hit Die: d6");
        wizardHitDie.setToolTipText("");
        jPanel1.add(wizardHitDie, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 830, 80, 30));

        wizardPrimAbility.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        wizardPrimAbility.setForeground(new java.awt.Color(255, 255, 255));
        wizardPrimAbility.setText("Primary Abilility: Intelligence");
        wizardPrimAbility.setToolTipText("");
        jPanel1.add(wizardPrimAbility, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 850, 190, 30));

        classTitle.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        classTitle.setForeground(new java.awt.Color(255, 255, 255));
        classTitle.setText("Class");
        classTitle.setToolTipText("");
        jPanel1.add(classTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 60, 30));

        paladinHitDie.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        paladinHitDie.setForeground(new java.awt.Color(255, 255, 255));
        paladinHitDie.setText("Hit Die: d10");
        paladinHitDie.setToolTipText("");
        jPanel1.add(paladinHitDie, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, 90, 30));

        strength.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        strength.setForeground(new java.awt.Color(255, 255, 255));
        strength.setText("Strength:");
        strength.setToolTipText("");
        jPanel1.add(strength, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 300, 80, 30));

        dexterity.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        dexterity.setForeground(new java.awt.Color(255, 255, 255));
        dexterity.setText("Dexterity:");
        dexterity.setToolTipText("");
        jPanel1.add(dexterity, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 350, 80, 30));

        constitution.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        constitution.setForeground(new java.awt.Color(255, 255, 255));
        constitution.setText("Constitution:");
        constitution.setToolTipText("");
        jPanel1.add(constitution, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 400, 80, 30));

        intelligence.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        intelligence.setForeground(new java.awt.Color(255, 255, 255));
        intelligence.setText("Intelligence:");
        intelligence.setToolTipText("");
        jPanel1.add(intelligence, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 450, 80, 30));

        wisdom.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        wisdom.setForeground(new java.awt.Color(255, 255, 255));
        wisdom.setText("Wisdom:");
        wisdom.setToolTipText("");
        jPanel1.add(wisdom, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 500, 80, 30));

        charisma.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        charisma.setForeground(new java.awt.Color(255, 255, 255));
        charisma.setText("Charisma:");
        charisma.setToolTipText("");
        jPanel1.add(charisma, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 550, 80, 30));

        charismaStat.setFont(new java.awt.Font("Old English Text MT", 1, 12)); // NOI18N
        charismaStat.setText("10");
        jPanel1.add(charismaStat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 550, 30, 30));

        strengthStat.setFont(new java.awt.Font("Old English Text MT", 1, 12)); // NOI18N
        strengthStat.setText("10");
        jPanel1.add(strengthStat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 300, 30, 30));

        DexterityStat.setFont(new java.awt.Font("Old English Text MT", 1, 12)); // NOI18N
        DexterityStat.setText("10");
        jPanel1.add(DexterityStat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 350, 30, 30));

        constitutionStat.setFont(new java.awt.Font("Old English Text MT", 1, 12)); // NOI18N
        constitutionStat.setText("10");
        jPanel1.add(constitutionStat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 400, 30, 30));

        intelligenceStat.setFont(new java.awt.Font("Old English Text MT", 1, 12)); // NOI18N
        intelligenceStat.setText("10");
        jPanel1.add(intelligenceStat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 450, 30, 30));

        wisdomStat.setFont(new java.awt.Font("Old English Text MT", 1, 12)); // NOI18N
        wisdomStat.setText("10");
        jPanel1.add(wisdomStat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 500, 30, 30));

        lessChar.setText("-");
        lessChar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessCharActionPerformed(evt);
            }
        });
        jPanel1.add(lessChar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 550, 50, 30));

        moreStr.setText("+");
        moreStr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreStrActionPerformed(evt);
            }
        });
        jPanel1.add(moreStr, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 300, 50, 30));

        moreDex.setText("+");
        moreDex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreDexActionPerformed(evt);
            }
        });
        jPanel1.add(moreDex, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 350, 50, 30));

        moreConst.setText("+");
        moreConst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreConstActionPerformed(evt);
            }
        });
        jPanel1.add(moreConst, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 400, 50, 30));

        moreInt.setText("+");
        moreInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreIntActionPerformed(evt);
            }
        });
        jPanel1.add(moreInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 450, 50, 30));

        moreWis.setText("+");
        moreWis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreWisActionPerformed(evt);
            }
        });
        jPanel1.add(moreWis, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 500, 50, 30));

        moreChar.setText("+");
        moreChar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreCharActionPerformed(evt);
            }
        });
        jPanel1.add(moreChar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 550, 50, 30));

        lessStr.setText("-");
        lessStr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessStrActionPerformed(evt);
            }
        });
        jPanel1.add(lessStr, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 300, 50, 30));

        lessDex.setText("-");
        lessDex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessDexActionPerformed(evt);
            }
        });
        jPanel1.add(lessDex, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 350, 50, 30));

        lessConst.setText("-");
        lessConst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessConstActionPerformed(evt);
            }
        });
        jPanel1.add(lessConst, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 400, 50, 30));

        lessInt.setText("-");
        lessInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessIntActionPerformed(evt);
            }
        });
        jPanel1.add(lessInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 450, 50, 30));

        lessWis.setText("-");
        lessWis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessWisActionPerformed(evt);
            }
        });
        jPanel1.add(lessWis, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 500, 50, 30));

        LastName7.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName7.setForeground(new java.awt.Color(255, 255, 255));
        LastName7.setText("Choose a Race:");
        LastName7.setToolTipText("");
        jPanel1.add(LastName7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 270, 30));

        LastName8.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName8.setForeground(new java.awt.Color(255, 255, 255));
        LastName8.setText("Choose a Class:");
        LastName8.setToolTipText("");
        jPanel1.add(LastName8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 120, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 260, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 260, 230, 20));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 260, 20));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 540, 20));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, 640));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 260, 10, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1285, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void humanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_humanButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_humanButtonActionPerformed

    private void halfOrcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_halfOrcButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_halfOrcButtonActionPerformed

    private void halfingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_halfingButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_halfingButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void wizardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wizardButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wizardButtonActionPerformed

    private void CharFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CharFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CharFNameActionPerformed

    private void CharLNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CharLNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CharLNameActionPerformed

    private void tieflingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tieflingButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tieflingButtonActionPerformed

    private void barbarianButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barbarianButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barbarianButtonActionPerformed

    private void bardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bardButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bardButtonActionPerformed

    private void clericButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clericButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clericButtonActionPerformed

    private void druidButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_druidButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_druidButtonActionPerformed

    private void fighterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fighterButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fighterButtonActionPerformed

    private void monkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monkButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monkButtonActionPerformed

    private void paladinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paladinButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paladinButtonActionPerformed

    private void rangerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rangerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rangerButtonActionPerformed

    private void rogueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rogueButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rogueButtonActionPerformed

    private void sorcerorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sorcerorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sorcerorButtonActionPerformed

    private void warlockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warlockButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_warlockButtonActionPerformed

    private void lessCharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessCharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lessCharActionPerformed

    private void moreStrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreStrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moreStrActionPerformed

    private void moreDexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreDexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moreDexActionPerformed

    private void moreConstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreConstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moreConstActionPerformed

    private void moreIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreIntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moreIntActionPerformed

    private void moreWisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreWisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moreWisActionPerformed

    private void moreCharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreCharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moreCharActionPerformed

    private void lessStrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessStrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lessStrActionPerformed

    private void lessDexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessDexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lessDexActionPerformed

    private void lessConstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessConstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lessConstActionPerformed

    private void lessIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessIntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lessIntActionPerformed

    private void lessWisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessWisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lessWisActionPerformed

    private void halfElfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_halfElfButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_halfElfButtonActionPerformed

    private void gnomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gnomeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gnomeButtonActionPerformed

    private void elfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elfButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elfButtonActionPerformed

    private void dwarfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dwarfButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dwarfButtonActionPerformed

    private void dragonBornButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dragonBornButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dragonBornButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel And;
    private javax.swing.JTextField CharFName;
    private javax.swing.JTextField CharLName;
    private javax.swing.JLabel CharacterCreation;
    private javax.swing.JTextField DexterityStat;
    private javax.swing.JLabel Dragons;
    private javax.swing.JLabel Fungeons;
    private javax.swing.JLabel LastName2;
    private javax.swing.JLabel LastName7;
    private javax.swing.JLabel LastName8;
    private javax.swing.JLabel barbHitDie;
    private javax.swing.JLabel barbPrimAbility;
    private javax.swing.JLabel barbSaves;
    private javax.swing.JButton barbarianButton;
    private javax.swing.JButton bardButton;
    private javax.swing.JLabel bardHitDie;
    private javax.swing.JLabel bardPrimAbility;
    private javax.swing.JLabel bardSaves;
    private javax.swing.JLabel baseStatsTitle;
    private javax.swing.JLabel charisma;
    private javax.swing.JTextField charismaStat;
    private javax.swing.JLabel classTitle;
    private javax.swing.JButton clericButton;
    private javax.swing.JLabel clericHitDie;
    private javax.swing.JLabel clericPrimAbility;
    private javax.swing.JLabel clericSaves;
    private javax.swing.JLabel constitution;
    private javax.swing.JTextField constitutionStat;
    private javax.swing.JLabel dexterity;
    private javax.swing.JButton dragonBornButton;
    private javax.swing.JLabel dragonBornChar;
    private javax.swing.JLabel dragonBornStr;
    private javax.swing.JButton druidButton;
    private javax.swing.JLabel druidHitDie;
    private javax.swing.JLabel druidPrimAbility;
    private javax.swing.JLabel druidSaves;
    private javax.swing.JButton dwarfButton;
    private javax.swing.JLabel dwarfConst;
    private javax.swing.JButton elfButton;
    private javax.swing.JLabel elfDex;
    private javax.swing.JLabel elfWis;
    private javax.swing.JLabel enterCharFName;
    private javax.swing.JLabel enterCharLName;
    private javax.swing.JButton fighterButton;
    private javax.swing.JLabel fighterHitDie;
    private javax.swing.JLabel fighterPrimAbility;
    private javax.swing.JLabel fighterSaves;
    private javax.swing.JButton gnomeButton;
    private javax.swing.JLabel gnomeInt;
    private javax.swing.JButton halfElfButton;
    private javax.swing.JLabel halfElfChar;
    private javax.swing.JButton halfOrcButton;
    private javax.swing.JLabel halfOrcConst;
    private javax.swing.JLabel halfOrdConst;
    private javax.swing.JButton halfingButton;
    private javax.swing.JLabel halfingDex;
    private javax.swing.JLabel humanAllAttr;
    private javax.swing.JButton humanButton;
    private javax.swing.JLabel intelligence;
    private javax.swing.JTextField intelligenceStat;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JButton lessChar;
    private javax.swing.JButton lessConst;
    private javax.swing.JButton lessDex;
    private javax.swing.JButton lessInt;
    private javax.swing.JButton lessStr;
    private javax.swing.JButton lessWis;
    private javax.swing.JButton monkButton;
    private javax.swing.JLabel monkHitDie;
    private javax.swing.JLabel monkPrimAbility;
    private javax.swing.JLabel monkSaves;
    private javax.swing.JButton moreChar;
    private javax.swing.JButton moreConst;
    private javax.swing.JButton moreDex;
    private javax.swing.JButton moreInt;
    private javax.swing.JButton moreStr;
    private javax.swing.JButton moreWis;
    private javax.swing.JButton paladinButton;
    private javax.swing.JLabel paladinHitDie;
    private javax.swing.JLabel paladinPrimAbility;
    private javax.swing.JLabel paladinSaves;
    private javax.swing.JLabel raceTitle;
    private javax.swing.JButton rangerButton;
    private javax.swing.JLabel rangerHitDie;
    private javax.swing.JLabel rangerPrimAbility;
    private javax.swing.JLabel rangerSaves;
    private javax.swing.JButton rogueButton;
    private javax.swing.JLabel rogueHitDie;
    private javax.swing.JLabel roguePrimAbility;
    private javax.swing.JLabel rogueSaves;
    private javax.swing.JButton sorcerorButton;
    private javax.swing.JLabel sorcerorHitDie;
    private javax.swing.JLabel sorcerorPrimAbility;
    private javax.swing.JLabel sorcerorSaves;
    private javax.swing.JLabel strength;
    private javax.swing.JTextField strengthStat;
    private javax.swing.JButton tieflingButton;
    private javax.swing.JLabel tieflingChar;
    private javax.swing.JLabel tieflingInt;
    private javax.swing.JButton warlockButton;
    private javax.swing.JLabel warlockHitDie;
    private javax.swing.JLabel warlockPrimAbility;
    private javax.swing.JLabel warlockSaves;
    private javax.swing.JLabel wisdom;
    private javax.swing.JTextField wisdomStat;
    private javax.swing.JButton wizardButton;
    private javax.swing.JLabel wizardHitDie;
    private javax.swing.JLabel wizardPrimAbility;
    private javax.swing.JLabel wizardSaves;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}