/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project2;

import java.util.Scanner;

/**
 *
 * @author rbhal
 */
public class PlayerGUI extends javax.swing.JFrame{

    /**
     * Creates new form PlayerGUI
     */
    public PlayerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        And = new javax.swing.JLabel();
        Fungeons = new javax.swing.JLabel();
        Dragons = new javax.swing.JLabel();
        CharacterCreation = new javax.swing.JLabel();
        FirstName = new javax.swing.JLabel();
        CharFirstName = new javax.swing.JTextField();
        LastName2 = new javax.swing.JLabel();
        LastName3 = new javax.swing.JLabel();
        LastName13 = new javax.swing.JLabel();
        LastName14 = new javax.swing.JLabel();
        LastName15 = new javax.swing.JLabel();
        LastName16 = new javax.swing.JLabel();
        LastName17 = new javax.swing.JLabel();
        LastName18 = new javax.swing.JLabel();
        LastName19 = new javax.swing.JLabel();
        LastName20 = new javax.swing.JLabel();
        LastName21 = new javax.swing.JLabel();
        LastName22 = new javax.swing.JLabel();
        LastName23 = new javax.swing.JLabel();
        LastName24 = new javax.swing.JLabel();
        LastName25 = new javax.swing.JLabel();
        CharFirstName1 = new javax.swing.JTextField();
        wizardButton = new javax.swing.JButton();
        dragonBornButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        dwarfButton = new javax.swing.JButton();
        elfButton = new javax.swing.JButton();
        gnomeButton = new javax.swing.JButton();
        halfElfButton = new javax.swing.JButton();
        halfingButton = new javax.swing.JButton();
        halfOrcButton = new javax.swing.JButton();
        humanButton = new javax.swing.JButton();
        LastName4 = new javax.swing.JLabel();
        LastName5 = new javax.swing.JLabel();
        tieflingButton = new javax.swing.JButton();
        barbarianButton = new javax.swing.JButton();
        bardButton = new javax.swing.JButton();
        clericButton = new javax.swing.JButton();
        druidButton = new javax.swing.JButton();
        fighterButton = new javax.swing.JButton();
        monkButton = new javax.swing.JButton();
        paladinButton = new javax.swing.JButton();
        rangerButton = new javax.swing.JButton();
        rogueButton = new javax.swing.JButton();
        sorcerorButton = new javax.swing.JButton();
        warlockButton = new javax.swing.JButton();
        LastName26 = new javax.swing.JLabel();
        LastName27 = new javax.swing.JLabel();
        LastName28 = new javax.swing.JLabel();
        LastName29 = new javax.swing.JLabel();
        LastName30 = new javax.swing.JLabel();
        LastName31 = new javax.swing.JLabel();
        LastName32 = new javax.swing.JLabel();
        LastName33 = new javax.swing.JLabel();
        LastName34 = new javax.swing.JLabel();
        LastName35 = new javax.swing.JLabel();
        LastName36 = new javax.swing.JLabel();
        LastName37 = new javax.swing.JLabel();
        LastName38 = new javax.swing.JLabel();
        LastName39 = new javax.swing.JLabel();
        LastName40 = new javax.swing.JLabel();
        LastName41 = new javax.swing.JLabel();
        LastName42 = new javax.swing.JLabel();
        LastName43 = new javax.swing.JLabel();
        LastName44 = new javax.swing.JLabel();
        LastName46 = new javax.swing.JLabel();
        LastName47 = new javax.swing.JLabel();
        LastName48 = new javax.swing.JLabel();
        LastName49 = new javax.swing.JLabel();
        LastName50 = new javax.swing.JLabel();
        LastName51 = new javax.swing.JLabel();
        LastName52 = new javax.swing.JLabel();
        LastName53 = new javax.swing.JLabel();
        LastName54 = new javax.swing.JLabel();
        LastName55 = new javax.swing.JLabel();
        LastName56 = new javax.swing.JLabel();
        LastName57 = new javax.swing.JLabel();
        LastName58 = new javax.swing.JLabel();
        LastName59 = new javax.swing.JLabel();
        LastName60 = new javax.swing.JLabel();
        LastName61 = new javax.swing.JLabel();
        LastName6 = new javax.swing.JLabel();
        LastName62 = new javax.swing.JLabel();
        LastName63 = new javax.swing.JLabel();
        LastName64 = new javax.swing.JLabel();
        LastName65 = new javax.swing.JLabel();
        LastName66 = new javax.swing.JLabel();
        LastName67 = new javax.swing.JLabel();
        LastName68 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        lessChar = new javax.swing.JButton();
        moreStr = new javax.swing.JButton();
        moreDex = new javax.swing.JButton();
        moreConst = new javax.swing.JButton();
        moreInt = new javax.swing.JButton();
        moreWis = new javax.swing.JButton();
        moreChar = new javax.swing.JButton();
        lessStr = new javax.swing.JButton();
        lessDex = new javax.swing.JButton();
        lessConst = new javax.swing.JButton();
        lessInt = new javax.swing.JButton();
        lessWis = new javax.swing.JButton();
        LastName7 = new javax.swing.JLabel();
        LastName8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(54, 6, 43));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        And.setFont(new java.awt.Font("Old English Text MT", 2, 70)); // NOI18N
        And.setForeground(new java.awt.Color(255, 255, 255));
        And.setText("&");
        And.setToolTipText("");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, And, org.jdesktop.beansbinding.ObjectProperty.create(), And, org.jdesktop.beansbinding.BeanProperty.create("labelFor"));
        bindingGroup.addBinding(binding);

        jPanel1.add(And, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 60, 60));

        Fungeons.setFont(new java.awt.Font("Old English Text MT", 1, 48)); // NOI18N
        Fungeons.setForeground(new java.awt.Color(255, 255, 255));
        Fungeons.setText("Fungeons");
        Fungeons.setToolTipText("");
        jPanel1.add(Fungeons, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 260, 60));

        Dragons.setFont(new java.awt.Font("Old English Text MT", 1, 48)); // NOI18N
        Dragons.setForeground(new java.awt.Color(255, 255, 255));
        Dragons.setText("Dragons");
        Dragons.setToolTipText("");
        jPanel1.add(Dragons, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 260, 60));

        CharacterCreation.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        CharacterCreation.setForeground(new java.awt.Color(255, 255, 255));
        CharacterCreation.setText("Character Creation");
        CharacterCreation.setToolTipText("");
        jPanel1.add(CharacterCreation, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 200, 30));

        FirstName.setFont(new java.awt.Font("Old English Text MT", 1, 18)); // NOI18N
        FirstName.setForeground(new java.awt.Color(255, 255, 255));
        FirstName.setText("Enter Character's First name:");
        FirstName.setToolTipText("");
        jPanel1.add(FirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 280, 20));

        CharFirstName.setFont(new java.awt.Font("Old English Text MT", 0, 12)); // NOI18N
        CharFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CharFirstNameActionPerformed(evt);
            }
        });
        jPanel1.add(CharFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 120, 20));

        LastName2.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName2.setForeground(new java.awt.Color(255, 255, 255));
        LastName2.setText("Choose base Stats:");
        LastName2.setToolTipText("");
        jPanel1.add(LastName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 270, 230, 30));

        LastName3.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        LastName3.setForeground(new java.awt.Color(255, 255, 255));
        LastName3.setText("Base Stats");
        LastName3.setToolTipText("");
        jPanel1.add(LastName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 220, 120, 30));

        LastName13.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName13.setForeground(new java.awt.Color(255, 255, 255));
        LastName13.setText("+1 Intelligence");
        LastName13.setToolTipText("");
        jPanel1.add(LastName13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 590, 100, 30));

        LastName14.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName14.setForeground(new java.awt.Color(255, 255, 255));
        LastName14.setText("+2 Strength");
        LastName14.setToolTipText("");
        jPanel1.add(LastName14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 80, 30));

        LastName15.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName15.setForeground(new java.awt.Color(255, 255, 255));
        LastName15.setText("+1 Charisma");
        LastName15.setToolTipText("");
        jPanel1.add(LastName15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 90, 30));

        LastName16.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName16.setForeground(new java.awt.Color(255, 255, 255));
        LastName16.setText("+2 Constitution");
        LastName16.setToolTipText("");
        jPanel1.add(LastName16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 100, 30));

        LastName17.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName17.setForeground(new java.awt.Color(255, 255, 255));
        LastName17.setText("+2 Dexterity");
        LastName17.setToolTipText("");
        jPanel1.add(LastName17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 100, 30));

        LastName18.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName18.setForeground(new java.awt.Color(255, 255, 255));
        LastName18.setText("+1 Wisdom");
        LastName18.setToolTipText("");
        jPanel1.add(LastName18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 100, 30));

        LastName19.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName19.setForeground(new java.awt.Color(255, 255, 255));
        LastName19.setText("+2 Intelligence");
        LastName19.setToolTipText("");
        jPanel1.add(LastName19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 100, 30));

        LastName20.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName20.setForeground(new java.awt.Color(255, 255, 255));
        LastName20.setText("+2 Charisma");
        LastName20.setToolTipText("");
        jPanel1.add(LastName20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 100, 30));

        LastName21.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName21.setForeground(new java.awt.Color(255, 255, 255));
        LastName21.setText("Saves: Dexterity & Charisma");
        LastName21.setToolTipText("");
        jPanel1.add(LastName21, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 200, 30));

        LastName22.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName22.setForeground(new java.awt.Color(255, 255, 255));
        LastName22.setText("+2 Strength");
        LastName22.setToolTipText("");
        jPanel1.add(LastName22, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 100, 30));

        LastName23.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName23.setForeground(new java.awt.Color(255, 255, 255));
        LastName23.setText("+1 Constitution");
        LastName23.setToolTipText("");
        jPanel1.add(LastName23, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 100, 30));

        LastName24.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName24.setForeground(new java.awt.Color(255, 255, 255));
        LastName24.setText("+1 to All Attributes");
        LastName24.setToolTipText("");
        jPanel1.add(LastName24, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 130, 30));

        LastName25.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName25.setForeground(new java.awt.Color(255, 255, 255));
        LastName25.setText("+2 Charisma");
        LastName25.setToolTipText("");
        jPanel1.add(LastName25, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 570, 90, 30));

        CharFirstName1.setFont(new java.awt.Font("Old English Text MT", 0, 12)); // NOI18N
        CharFirstName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CharFirstName1ActionPerformed(evt);
            }
        });
        jPanel1.add(CharFirstName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 120, 20));

        wizardButton.setBackground(new java.awt.Color(204, 204, 204));
        wizardButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        wizardButton.setText("Wizard");
        wizardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wizardButtonActionPerformed(evt);
            }
        });
        jPanel1.add(wizardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 800, 120, 30));

        dragonBornButton.setBackground(new java.awt.Color(204, 204, 204));
        dragonBornButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        dragonBornButton.setText("Dragonborn");
        dragonBornButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dragonBornButtonActionPerformed(evt);
            }
        });
        jPanel1.add(dragonBornButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 120, 30));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        jButton3.setText("Dragonborn");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 120, 30));

        dwarfButton.setBackground(new java.awt.Color(204, 204, 204));
        dwarfButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        dwarfButton.setText("Dwarf");
        dwarfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dwarfButtonActionPerformed(evt);
            }
        });
        jPanel1.add(dwarfButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 120, 30));

        elfButton.setBackground(new java.awt.Color(204, 204, 204));
        elfButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        elfButton.setText("Elf");
        elfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elfButtonActionPerformed(evt);
            }
        });
        jPanel1.add(elfButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 120, 30));

        gnomeButton.setBackground(new java.awt.Color(204, 204, 204));
        gnomeButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        gnomeButton.setText("Gnome");
        gnomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gnomeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(gnomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 120, 30));

        halfElfButton.setBackground(new java.awt.Color(204, 204, 204));
        halfElfButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        halfElfButton.setText("Half-Elf");
        halfElfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                halfElfButtonActionPerformed(evt);
            }
        });
        jPanel1.add(halfElfButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 120, 30));

        halfingButton.setBackground(new java.awt.Color(204, 204, 204));
        halfingButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        halfingButton.setText("Halfing");
        halfingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                halfingButtonActionPerformed(evt);
            }
        });
        jPanel1.add(halfingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 120, 30));

        halfOrcButton.setBackground(new java.awt.Color(204, 204, 204));
        halfOrcButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        halfOrcButton.setText("Half-Orc");
        halfOrcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                halfOrcButtonActionPerformed(evt);
            }
        });
        jPanel1.add(halfOrcButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 120, 30));

        humanButton.setBackground(new java.awt.Color(204, 204, 204));
        humanButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        humanButton.setText("Human");
        humanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                humanButtonActionPerformed(evt);
            }
        });
        jPanel1.add(humanButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 120, 30));

        LastName4.setFont(new java.awt.Font("Old English Text MT", 1, 18)); // NOI18N
        LastName4.setForeground(new java.awt.Color(255, 255, 255));
        LastName4.setText("Enter Character's last name:");
        LastName4.setToolTipText("");
        jPanel1.add(LastName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 270, 30));

        LastName5.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        LastName5.setForeground(new java.awt.Color(255, 255, 255));
        LastName5.setText("Race");
        LastName5.setToolTipText("");
        jPanel1.add(LastName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 60, 30));

        tieflingButton.setBackground(new java.awt.Color(204, 204, 204));
        tieflingButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        tieflingButton.setText("Tiefling");
        tieflingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tieflingButtonActionPerformed(evt);
            }
        });
        jPanel1.add(tieflingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 540, 120, 30));

        barbarianButton.setBackground(new java.awt.Color(204, 204, 204));
        barbarianButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        barbarianButton.setText("Bardarian");
        barbarianButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barbarianButtonActionPerformed(evt);
            }
        });
        jPanel1.add(barbarianButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 120, 30));

        bardButton.setBackground(new java.awt.Color(204, 204, 204));
        bardButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        bardButton.setText("Bard");
        bardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bardButtonActionPerformed(evt);
            }
        });
        jPanel1.add(bardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 120, 30));

        clericButton.setBackground(new java.awt.Color(204, 204, 204));
        clericButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        clericButton.setText("Cleric");
        clericButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clericButtonActionPerformed(evt);
            }
        });
        jPanel1.add(clericButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, 120, 30));

        druidButton.setBackground(new java.awt.Color(204, 204, 204));
        druidButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        druidButton.setText("Druid");
        druidButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                druidButtonActionPerformed(evt);
            }
        });
        jPanel1.add(druidButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 600, 120, 30));

        fighterButton.setBackground(new java.awt.Color(204, 204, 204));
        fighterButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        fighterButton.setText("Fighter");
        fighterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fighterButtonActionPerformed(evt);
            }
        });
        jPanel1.add(fighterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 700, 120, 30));

        monkButton.setBackground(new java.awt.Color(204, 204, 204));
        monkButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        monkButton.setText("Monk");
        monkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monkButtonActionPerformed(evt);
            }
        });
        jPanel1.add(monkButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 800, 120, 30));

        paladinButton.setBackground(new java.awt.Color(204, 204, 204));
        paladinButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        paladinButton.setText("Paladin");
        paladinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paladinButtonActionPerformed(evt);
            }
        });
        jPanel1.add(paladinButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 120, 30));

        rangerButton.setBackground(new java.awt.Color(204, 204, 204));
        rangerButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        rangerButton.setText("Ranger");
        rangerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rangerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(rangerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 120, 30));

        rogueButton.setBackground(new java.awt.Color(204, 204, 204));
        rogueButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        rogueButton.setText("Rogue");
        rogueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rogueButtonActionPerformed(evt);
            }
        });
        jPanel1.add(rogueButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 500, 120, 30));

        sorcerorButton.setBackground(new java.awt.Color(204, 204, 204));
        sorcerorButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        sorcerorButton.setText("Sorceror");
        sorcerorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sorcerorButtonActionPerformed(evt);
            }
        });
        jPanel1.add(sorcerorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 600, 120, 30));

        warlockButton.setBackground(new java.awt.Color(204, 204, 204));
        warlockButton.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        warlockButton.setText("Warlock");
        warlockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warlockButtonActionPerformed(evt);
            }
        });
        jPanel1.add(warlockButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 700, 120, 30));

        LastName26.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName26.setForeground(new java.awt.Color(255, 255, 255));
        LastName26.setText("+2 Dexterity");
        LastName26.setToolTipText("");
        jPanel1.add(LastName26, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 100, 30));

        LastName27.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName27.setForeground(new java.awt.Color(255, 255, 255));
        LastName27.setText("Hit Die: d8");
        LastName27.setToolTipText("");
        jPanel1.add(LastName27, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 80, 30));

        LastName28.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName28.setForeground(new java.awt.Color(255, 255, 255));
        LastName28.setText("Primary Abilility: Charisma");
        LastName28.setToolTipText("");
        jPanel1.add(LastName28, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 180, 30));

        LastName29.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName29.setForeground(new java.awt.Color(255, 255, 255));
        LastName29.setText("Hit Die: d12");
        LastName29.setToolTipText("");
        jPanel1.add(LastName29, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 90, 30));

        LastName30.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName30.setForeground(new java.awt.Color(255, 255, 255));
        LastName30.setText("Primary Abilility: Strength");
        LastName30.setToolTipText("");
        jPanel1.add(LastName30, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 180, 30));

        LastName31.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName31.setForeground(new java.awt.Color(255, 255, 255));
        LastName31.setText("Saves: Strength & Constitution");
        LastName31.setToolTipText("");
        jPanel1.add(LastName31, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 210, 30));

        LastName32.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName32.setForeground(new java.awt.Color(255, 255, 255));
        LastName32.setText("Saves: Wisdom & Charisma");
        LastName32.setToolTipText("");
        jPanel1.add(LastName32, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 570, 190, 30));

        LastName33.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName33.setForeground(new java.awt.Color(255, 255, 255));
        LastName33.setText("Hit Die: d8");
        LastName33.setToolTipText("");
        jPanel1.add(LastName33, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, 80, 30));

        LastName34.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName34.setForeground(new java.awt.Color(255, 255, 255));
        LastName34.setText("Primary Abilility: Wisdom");
        LastName34.setToolTipText("");
        jPanel1.add(LastName34, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 550, 170, 30));

        LastName35.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName35.setForeground(new java.awt.Color(255, 255, 255));
        LastName35.setText("Saves: Intelligence & Wisdom");
        LastName35.setToolTipText("");
        jPanel1.add(LastName35, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 670, 200, 30));

        LastName36.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName36.setForeground(new java.awt.Color(255, 255, 255));
        LastName36.setText("Hit Die: d8");
        LastName36.setToolTipText("");
        jPanel1.add(LastName36, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 630, 100, 30));

        LastName37.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName37.setForeground(new java.awt.Color(255, 255, 255));
        LastName37.setText("Primary Abilility: Wisdom");
        LastName37.setToolTipText("");
        jPanel1.add(LastName37, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 650, 170, 30));

        LastName38.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName38.setForeground(new java.awt.Color(255, 255, 255));
        LastName38.setText("Saves: Strength & Constitution");
        LastName38.setToolTipText("");
        jPanel1.add(LastName38, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 770, 210, 30));

        LastName39.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName39.setForeground(new java.awt.Color(255, 255, 255));
        LastName39.setText("Hit Die: d10");
        LastName39.setToolTipText("");
        jPanel1.add(LastName39, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 730, 100, 30));

        LastName40.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName40.setForeground(new java.awt.Color(255, 255, 255));
        LastName40.setText("Primary Abilility: Strength or Dexterity");
        LastName40.setToolTipText("");
        jPanel1.add(LastName40, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 750, 250, 30));

        LastName41.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName41.setForeground(new java.awt.Color(255, 255, 255));
        LastName41.setText("Saves: Strength & Dexterity");
        LastName41.setToolTipText("");
        jPanel1.add(LastName41, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 870, 190, 30));

        LastName42.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName42.setForeground(new java.awt.Color(255, 255, 255));
        LastName42.setText("Hit Die: d8");
        LastName42.setToolTipText("");
        jPanel1.add(LastName42, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 830, 100, 30));

        LastName43.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName43.setForeground(new java.awt.Color(255, 255, 255));
        LastName43.setText("Primary Abilility: Dexterity & Wisdom");
        LastName43.setToolTipText("");
        jPanel1.add(LastName43, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 850, 190, 30));

        LastName44.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName44.setForeground(new java.awt.Color(255, 255, 255));
        LastName44.setText("Saves: Wisdom & Charisma");
        LastName44.setToolTipText("");
        jPanel1.add(LastName44, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 190, 30));

        LastName46.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName46.setForeground(new java.awt.Color(255, 255, 255));
        LastName46.setText("Primary Abilility: Strength & Charisma");
        LastName46.setToolTipText("");
        jPanel1.add(LastName46, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, 250, 30));

        LastName47.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName47.setForeground(new java.awt.Color(255, 255, 255));
        LastName47.setText("Saves: Strength & Dexterity");
        LastName47.setToolTipText("");
        jPanel1.add(LastName47, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 470, 190, 30));

        LastName48.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName48.setForeground(new java.awt.Color(255, 255, 255));
        LastName48.setText("Hit Die: d10");
        LastName48.setToolTipText("");
        jPanel1.add(LastName48, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, 90, 30));

        LastName49.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName49.setForeground(new java.awt.Color(255, 255, 255));
        LastName49.setText("Primary Abilility: Dexterity & Wisdom");
        LastName49.setToolTipText("");
        jPanel1.add(LastName49, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, 250, 30));

        LastName50.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName50.setForeground(new java.awt.Color(255, 255, 255));
        LastName50.setText("Saves: Dexterity & Intelligence");
        LastName50.setToolTipText("");
        jPanel1.add(LastName50, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 570, 210, 30));

        LastName51.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName51.setForeground(new java.awt.Color(255, 255, 255));
        LastName51.setText("Hit Die: d8");
        LastName51.setToolTipText("");
        jPanel1.add(LastName51, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 530, 80, 30));

        LastName52.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName52.setForeground(new java.awt.Color(255, 255, 255));
        LastName52.setText("Primary Abilility: Dexterity ");
        LastName52.setToolTipText("");
        jPanel1.add(LastName52, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 550, 180, 30));

        LastName53.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName53.setForeground(new java.awt.Color(255, 255, 255));
        LastName53.setText("Saves: Constitution & Charisma");
        LastName53.setToolTipText("");
        jPanel1.add(LastName53, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 670, 210, 30));

        LastName54.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName54.setForeground(new java.awt.Color(255, 255, 255));
        LastName54.setText("Hit Die: d6");
        LastName54.setToolTipText("");
        jPanel1.add(LastName54, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 630, 80, 30));

        LastName55.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName55.setForeground(new java.awt.Color(255, 255, 255));
        LastName55.setText("Primary Abilility: Charisma");
        LastName55.setToolTipText("");
        jPanel1.add(LastName55, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 650, 180, 30));

        LastName56.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName56.setForeground(new java.awt.Color(255, 255, 255));
        LastName56.setText("Saves: Wisdom & Charisma");
        LastName56.setToolTipText("");
        jPanel1.add(LastName56, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 770, 190, 30));

        LastName57.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName57.setForeground(new java.awt.Color(255, 255, 255));
        LastName57.setText("Hit Die: d8");
        LastName57.setToolTipText("");
        jPanel1.add(LastName57, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 730, 80, 30));

        LastName58.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName58.setForeground(new java.awt.Color(255, 255, 255));
        LastName58.setText("Primary Abilility: Charisma");
        LastName58.setToolTipText("");
        jPanel1.add(LastName58, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 750, 180, 30));

        LastName59.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName59.setForeground(new java.awt.Color(255, 255, 255));
        LastName59.setText("Saves: Intelligence & Wisdom");
        LastName59.setToolTipText("");
        jPanel1.add(LastName59, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 870, 200, 30));

        LastName60.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName60.setForeground(new java.awt.Color(255, 255, 255));
        LastName60.setText("Hit Die: d6");
        LastName60.setToolTipText("");
        jPanel1.add(LastName60, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 830, 80, 30));

        LastName61.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName61.setForeground(new java.awt.Color(255, 255, 255));
        LastName61.setText("Primary Abilility: Intelligence");
        LastName61.setToolTipText("");
        jPanel1.add(LastName61, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 850, 190, 30));

        LastName6.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        LastName6.setForeground(new java.awt.Color(255, 255, 255));
        LastName6.setText("Class");
        LastName6.setToolTipText("");
        jPanel1.add(LastName6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 60, 30));

        LastName62.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName62.setForeground(new java.awt.Color(255, 255, 255));
        LastName62.setText("Hit Die: d10");
        LastName62.setToolTipText("");
        jPanel1.add(LastName62, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, 90, 30));

        LastName63.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName63.setForeground(new java.awt.Color(255, 255, 255));
        LastName63.setText("Strength:");
        LastName63.setToolTipText("");
        jPanel1.add(LastName63, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 300, 80, 30));

        LastName64.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName64.setForeground(new java.awt.Color(255, 255, 255));
        LastName64.setText("Dexterity:");
        LastName64.setToolTipText("");
        jPanel1.add(LastName64, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 350, 80, 30));

        LastName65.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName65.setForeground(new java.awt.Color(255, 255, 255));
        LastName65.setText("Constitution:");
        LastName65.setToolTipText("");
        jPanel1.add(LastName65, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 400, 80, 30));

        LastName66.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName66.setForeground(new java.awt.Color(255, 255, 255));
        LastName66.setText("Intelligence:");
        LastName66.setToolTipText("");
        jPanel1.add(LastName66, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 450, 80, 30));

        LastName67.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName67.setForeground(new java.awt.Color(255, 255, 255));
        LastName67.setText("Wisdom:");
        LastName67.setToolTipText("");
        jPanel1.add(LastName67, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 500, 80, 30));

        LastName68.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName68.setForeground(new java.awt.Color(255, 255, 255));
        LastName68.setText("Charisma:");
        LastName68.setToolTipText("");
        jPanel1.add(LastName68, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 550, 80, 30));

        jTextField1.setFont(new java.awt.Font("Old English Text MT", 1, 12)); // NOI18N
        jTextField1.setText("10");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 550, 30, 30));

        jTextField2.setFont(new java.awt.Font("Old English Text MT", 1, 12)); // NOI18N
        jTextField2.setText("10");
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 300, 30, 30));

        jTextField3.setFont(new java.awt.Font("Old English Text MT", 1, 12)); // NOI18N
        jTextField3.setText("10");
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 350, 30, 30));

        jTextField4.setFont(new java.awt.Font("Old English Text MT", 1, 12)); // NOI18N
        jTextField4.setText("10");
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 400, 30, 30));

        jTextField5.setFont(new java.awt.Font("Old English Text MT", 1, 12)); // NOI18N
        jTextField5.setText("10");
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 450, 30, 30));

        jTextField6.setFont(new java.awt.Font("Old English Text MT", 1, 12)); // NOI18N
        jTextField6.setText("10");
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 500, 30, 30));

        lessChar.setText("-");
        lessChar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessCharActionPerformed(evt);
            }
        });
        jPanel1.add(lessChar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 550, 50, 30));

        moreStr.setText("+");
        moreStr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreStrActionPerformed(evt);
            }
        });
        jPanel1.add(moreStr, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 300, 50, 30));

        moreDex.setText("+");
        moreDex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreDexActionPerformed(evt);
            }
        });
        jPanel1.add(moreDex, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 350, 50, 30));

        moreConst.setText("+");
        moreConst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreConstActionPerformed(evt);
            }
        });
        jPanel1.add(moreConst, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 400, 50, 30));

        moreInt.setText("+");
        moreInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreIntActionPerformed(evt);
            }
        });
        jPanel1.add(moreInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 450, 50, 30));

        moreWis.setText("+");
        moreWis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreWisActionPerformed(evt);
            }
        });
        jPanel1.add(moreWis, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 500, 50, 30));

        moreChar.setText("+");
        moreChar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreCharActionPerformed(evt);
            }
        });
        jPanel1.add(moreChar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 550, 50, 30));

        lessStr.setText("-");
        lessStr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessStrActionPerformed(evt);
            }
        });
        jPanel1.add(lessStr, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 300, 50, 30));

        lessDex.setText("-");
        lessDex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessDexActionPerformed(evt);
            }
        });
        jPanel1.add(lessDex, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 350, 50, 30));

        lessConst.setText("-");
        lessConst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessConstActionPerformed(evt);
            }
        });
        jPanel1.add(lessConst, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 400, 50, 30));

        lessInt.setText("-");
        lessInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessIntActionPerformed(evt);
            }
        });
        jPanel1.add(lessInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 450, 50, 30));

        lessWis.setText("-");
        lessWis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessWisActionPerformed(evt);
            }
        });
        jPanel1.add(lessWis, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 500, 50, 30));

        LastName7.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName7.setForeground(new java.awt.Color(255, 255, 255));
        LastName7.setText("Choose a Race:");
        LastName7.setToolTipText("");
        jPanel1.add(LastName7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 270, 30));

        LastName8.setFont(new java.awt.Font("Old English Text MT", 1, 14)); // NOI18N
        LastName8.setForeground(new java.awt.Color(255, 255, 255));
        LastName8.setText("Choose a Class:");
        LastName8.setToolTipText("");
        jPanel1.add(LastName8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 120, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 260, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 260, 230, 20));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 260, 20));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 540, 20));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, 640));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 260, 10, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1285, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void humanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_humanButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_humanButtonActionPerformed

    private void halfOrcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_halfOrcButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_halfOrcButtonActionPerformed

    private void halfingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_halfingButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_halfingButtonActionPerformed

    private void halfElfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_halfElfButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_halfElfButtonActionPerformed

    private void gnomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gnomeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gnomeButtonActionPerformed

    private void elfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elfButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elfButtonActionPerformed

    private void dwarfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dwarfButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dwarfButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void dragonBornButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dragonBornButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dragonBornButtonActionPerformed

    private void wizardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wizardButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wizardButtonActionPerformed

    private void CharFirstName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CharFirstName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CharFirstName1ActionPerformed

    private void CharFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CharFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CharFirstNameActionPerformed

    private void tieflingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tieflingButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tieflingButtonActionPerformed

    private void barbarianButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barbarianButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barbarianButtonActionPerformed

    private void bardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bardButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bardButtonActionPerformed

    private void clericButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clericButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clericButtonActionPerformed

    private void druidButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_druidButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_druidButtonActionPerformed

    private void fighterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fighterButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fighterButtonActionPerformed

    private void monkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monkButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monkButtonActionPerformed

    private void paladinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paladinButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paladinButtonActionPerformed

    private void rangerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rangerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rangerButtonActionPerformed

    private void rogueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rogueButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rogueButtonActionPerformed

    private void sorcerorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sorcerorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sorcerorButtonActionPerformed

    private void warlockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warlockButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_warlockButtonActionPerformed

    private void lessCharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessCharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lessCharActionPerformed

    private void moreStrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreStrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moreStrActionPerformed

    private void moreDexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreDexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moreDexActionPerformed

    private void moreConstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreConstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moreConstActionPerformed

    private void moreIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreIntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moreIntActionPerformed

    private void moreWisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreWisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moreWisActionPerformed

    private void moreCharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreCharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moreCharActionPerformed

    private void lessStrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessStrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lessStrActionPerformed

    private void lessDexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessDexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lessDexActionPerformed

    private void lessConstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessConstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lessConstActionPerformed

    private void lessIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessIntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lessIntActionPerformed

    private void lessWisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessWisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lessWisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel And;
    private javax.swing.JTextField CharFirstName;
    private javax.swing.JTextField CharFirstName1;
    private javax.swing.JLabel CharacterCreation;
    private javax.swing.JLabel Dragons;
    private javax.swing.JLabel FirstName;
    private javax.swing.JLabel Fungeons;
    private javax.swing.JLabel LastName13;
    private javax.swing.JLabel LastName14;
    private javax.swing.JLabel LastName15;
    private javax.swing.JLabel LastName16;
    private javax.swing.JLabel LastName17;
    private javax.swing.JLabel LastName18;
    private javax.swing.JLabel LastName19;
    private javax.swing.JLabel LastName2;
    private javax.swing.JLabel LastName20;
    private javax.swing.JLabel LastName21;
    private javax.swing.JLabel LastName22;
    private javax.swing.JLabel LastName23;
    private javax.swing.JLabel LastName24;
    private javax.swing.JLabel LastName25;
    private javax.swing.JLabel LastName26;
    private javax.swing.JLabel LastName27;
    private javax.swing.JLabel LastName28;
    private javax.swing.JLabel LastName29;
    private javax.swing.JLabel LastName3;
    private javax.swing.JLabel LastName30;
    private javax.swing.JLabel LastName31;
    private javax.swing.JLabel LastName32;
    private javax.swing.JLabel LastName33;
    private javax.swing.JLabel LastName34;
    private javax.swing.JLabel LastName35;
    private javax.swing.JLabel LastName36;
    private javax.swing.JLabel LastName37;
    private javax.swing.JLabel LastName38;
    private javax.swing.JLabel LastName39;
    private javax.swing.JLabel LastName4;
    private javax.swing.JLabel LastName40;
    private javax.swing.JLabel LastName41;
    private javax.swing.JLabel LastName42;
    private javax.swing.JLabel LastName43;
    private javax.swing.JLabel LastName44;
    private javax.swing.JLabel LastName46;
    private javax.swing.JLabel LastName47;
    private javax.swing.JLabel LastName48;
    private javax.swing.JLabel LastName49;
    private javax.swing.JLabel LastName5;
    private javax.swing.JLabel LastName50;
    private javax.swing.JLabel LastName51;
    private javax.swing.JLabel LastName52;
    private javax.swing.JLabel LastName53;
    private javax.swing.JLabel LastName54;
    private javax.swing.JLabel LastName55;
    private javax.swing.JLabel LastName56;
    private javax.swing.JLabel LastName57;
    private javax.swing.JLabel LastName58;
    private javax.swing.JLabel LastName59;
    private javax.swing.JLabel LastName6;
    private javax.swing.JLabel LastName60;
    private javax.swing.JLabel LastName61;
    private javax.swing.JLabel LastName62;
    private javax.swing.JLabel LastName63;
    private javax.swing.JLabel LastName64;
    private javax.swing.JLabel LastName65;
    private javax.swing.JLabel LastName66;
    private javax.swing.JLabel LastName67;
    private javax.swing.JLabel LastName68;
    private javax.swing.JLabel LastName7;
    private javax.swing.JLabel LastName8;
    private javax.swing.JButton barbarianButton;
    private javax.swing.JButton bardButton;
    private javax.swing.JButton clericButton;
    private javax.swing.JButton dragonBornButton;
    private javax.swing.JButton druidButton;
    private javax.swing.JButton dwarfButton;
    private javax.swing.JButton elfButton;
    private javax.swing.JButton fighterButton;
    private javax.swing.JButton gnomeButton;
    private javax.swing.JButton halfElfButton;
    private javax.swing.JButton halfOrcButton;
    private javax.swing.JButton halfingButton;
    private javax.swing.JButton humanButton;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JButton lessChar;
    private javax.swing.JButton lessConst;
    private javax.swing.JButton lessDex;
    private javax.swing.JButton lessInt;
    private javax.swing.JButton lessStr;
    private javax.swing.JButton lessWis;
    private javax.swing.JButton monkButton;
    private javax.swing.JButton moreChar;
    private javax.swing.JButton moreConst;
    private javax.swing.JButton moreDex;
    private javax.swing.JButton moreInt;
    private javax.swing.JButton moreStr;
    private javax.swing.JButton moreWis;
    private javax.swing.JButton paladinButton;
    private javax.swing.JButton rangerButton;
    private javax.swing.JButton rogueButton;
    private javax.swing.JButton sorcerorButton;
    private javax.swing.JButton tieflingButton;
    private javax.swing.JButton warlockButton;
    private javax.swing.JButton wizardButton;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}